name: Build & Deploy Spring App #name for workflows

on: ##when action is triggered
  push:
    branches:
      - test-ci-cd
jobs:
  build-deploy:
    name: Build And Deploy App Spring
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JKD 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Build & Test
        run: chmod +x ./mvnw && ./mvnw clean install -f pom.xml -DskipTests
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build & Push to Docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/video-chat-java-btl:latest


